[package]
name = "example-cli-app"
version = "0.1.0"
authors = ["Tan Quach <tan.quach@birchwoodlangham.com>"]

[dependencies]
config = "0.9"
structopt = "0.2"
serde = "1.0.70"
serde_derive = "1.0.70"
